### ISSUE TITLE
Tabular file

### ISSUE THREAD

**Issue by annefou** [deepthi1107/Outreachy_contribution_Galaxy_Community.github.io#2]
That would be very nice to explain why you have chosen to display data at 00:00:00 UTC. What is improtant at this time?

also, you have chosen one latitude and a few longitude: what is the name of the are you selected?

**Comment by deepthi1107** [comment]
sure @annefou

**Comment by deepthi1107** [comment]
@annefou, for the tabular data I have selected time from 00:00:00 to 16:00:00, the file contains 2,40,000 lines, which displays the air temp for every particular lat, lon, and time. I have chosen lat and lon to display the data related to India ( latitudes 8°4'N and 37°6'N and longitudes 68°7'E and 97°25'E.), I have updated the web to include a link to download the tabular file. Guide me, if I am wrong at any place.
Thank You

**Comment by annefou** [comment]
I am not sure I am looking at the right file/info. I only see data for 2022-03-31 00:00:00 UTC and for different location. around latitude=37.75, longitude=68.25.

**Comment by deepthi1107** [comment]
Actually, in the image, it is just a sample. You can view the entire tabular file either by downloading or viewing the file by clicking on the links provided @annefou 
![image](https://user-images.githubusercontent.com/79050917/163012753-6e562166-3bce-4eaa-972f-77825b54b3ac.png)

**Comment by deepthi1107** [comment]
@annefou, by clicking on the Tabular link to view the data, then scroll down slowly to view the entire file.

**Comment by deepthi1107** [comment]
https://usegalaxy.eu/datasets/4838ba20a6d86765e016c4dc47848e9e/display/?preview=True
@annefou 
This is the link to view the file which I have mentioned on the page where by scrolling down slowly, one can view the file.

**Comment by annefou** [comment]
Ok. Could you select one single location (town/city, etc.) where you live? Then select one hour that you think is relevant for this location. For instance, I live in Oslo (Norway) and soon spring is coming so I would probably select the time where we have the minimum value. Does it make sense?

**Comment by deepthi1107** [comment]
sure, @annefou, I would do that and get back to you.

**Comment by deepthi1107** [comment]
Actually @annefou, I have selected lat and lon of India, but as guided by you, now I would like to extract the data of my area that I live in. Area name is Hyderabad (capital city of Telangana, India)

**Comment by deepthi1107** [comment]
Should I keep the previous links and image of the tabular file or remove them @annefou

**Comment by annefou** [comment]
I think you can replace it because online it is difficult to browse such big file. And looking at a portion does not help much. Many thanks!

**Comment by deepthi1107** [comment]
Sure, I would do that @annefou, Thank you.

**Comment by deepthi1107** [comment]
Shall I remove the related steps in usegalaxy.eu also or keep the same? @annefou

**Comment by deepthi1107** [comment]
![image](https://user-images.githubusercontent.com/79050917/163026125-a1e5d131-63d6-4e1d-8097-2674b9e4cc74.png)
 
 This is the file I have got for Hyderabad city. Is this file good to go? 
Lat and Lon for Hyderabad city is 17.3850° N, 78.4867° E, hence, I have chosen which is closer to that.
I have updated the webpage. Have a look, any changes to make that would be appreciated or this is good to go. Give me feedback after the view the updated webpage.
Thank you @annefou

**Comment by annefou** [comment]
> Shall I remove the related steps in usegalaxy.eu also or keep the same? @annefou

No need to change anything in Galaxy.

**Comment by annefou** [comment]
> ![image](https://user-images.githubusercontent.com/79050917/163026125-a1e5d131-63d6-4e1d-8097-2674b9e4cc74.png)
> 
> This is the file I have got for Hyderabad city. Is this file good to go? Lat and Lon for Hyderabad city is 17.3850° N, 78.4867° E, hence, I have chosen which is closer to that. I have updated the webpage. Have a look, any changes to make that would be appreciated or this is good to go. Give me feedback after the view the updated webpage. Thank you @annefou

Perfect!

**Comment by deepthi1107** [comment]
Thank you @annefou

**Comment by deepthi1107** [comment]
Sure, I wont change anything in Galaxy Europe @annefou

**Comment by deepthi1107** [comment]
I think this issue has been sorted. Can I close this issue or @annefou, you will close this issue?

**Comment by deepthi1107** [comment]
Thanks, @annefou, for your assistance to slove the issue.
